### PR TITLE
icons can handle class lists

### PR DESCRIPTION
**Pull request by tcoopman**
This allows for something like:

```elixir
      <Phosphoricons.LiveView.icon
        name={@icon}
        class={[
          @current && "text-gray-500",
          !@current && "text-gray-400 group:hover-text-gray-500",
          "mr-4 md:mr-3 flex-shrink-0 h-6 w-6"
        ]}
      />
```

### CODE REVIEW

**Comment by noozo** [comment]
@tcoopman says 5000+ lines changed. sorry for only looking at this now, but any chance you could change it to support our latest update 0.2.0 (about to be merged).

**Comment by noozo** [comment]
> @tcoopman says 5000+ lines changed. sorry for only looking at this now, but any chance you could change it to support our latest update 0.2.0 (about to be merged).

We just updated to the latest icons. if you can, remove them from your PR. would love to have your class list changes <3

**Comment by noozo** [comment]
Closing this and implementing in separate PR.

**Comment by noozo** [comment]
https://github.com/noozo/phosphoricons_elixir/pull/5

**Comment by tcoopman** [comment]
@noozo sorry I kept on pushing to the same branch on my own, that's why so many changes happened.
Thanks for fixing!

**Pull request closed without merging**
